name: Validate Pull Request

on: [push, pull_request]

jobs:
  lint:
    name: Lint lockdir, generate opam files, autoformat
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Install esy
        run: npm install -g esy
      - name: Update lockdir
        run: |
          echo '{}' > esy.json
          esy add @opam/ocamlformat @opam/dune
      - name: Build dependencies
        run: esy build-dependencies
      - name: Format files
        run: esy dune build @fmt --auto-promote
      - name: Display status should be clean
        run: git diff
